# Generated by Django 3.2.7 on 2021-09-28 11:11

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('cbc_elec', '0002_alter_voter_cnic'),
    ]

    operations = [
        migrations.AddField(
            model_name='voter',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='voter',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
