# Generated by Django 3.2.7 on 2021-09-28 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cbc_elec', '0003_auto_20210928_1111'),
    ]

    operations = [
        migrations.AlterField(
            model_name='voter',
            name='cnic',
            field=models.BigIntegerField(unique=True),
        ),
    ]
