# Generated by Django 3.2.7 on 2021-09-28 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cbc_elec', '0004_alter_voter_cnic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='voter',
            name='address',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='voter',
            name='phase',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
